# Generated by Django 4.2.20 on 2025-04-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test3',
            old_name='avatar',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='test3',
            old_name='name',
            new_name='username',
        ),
    ]
