# Generated by Django 4.2.20 on 2025-04-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_rename_avatar_test3_pwd_rename_name_test3_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test3',
            name='pwd',
            field=models.CharField(max_length=20),
        ),
    ]
