# Generated by Django 4.2.20 on 2025-04-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_alter_test3_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
