# Generated by Django 4.2.20 on 2025-04-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('sms_code', models.CharField(max_length=6, null=True)),
                ('sms_code_expire', models.DateTimeField(null=True)),
            ],
        ),
    ]
